### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by gvegayon** [UT-IDDynamics/wepidemics#1]
@Keeganlt @jaywl I think we could have an automated pipeline that grabs a description file and organizes it in a fancy way, e.g., have a file like:

```yaml
​name: epiworld
DOI: ...
software: c++
software-url: ...
description: epiworld...
type: software
keywords: abm, networks, ...
```

```yaml
​​name: AFancyMethod...
DOI: ...
software: -
software-url: -
description: A FancyMethod is ...
type: method
keywords: Rt, R
```

Then I can have a pipeline that grabs those files and builds the website. I have done that [in the past](https://github.com/gvegayon/talks) having a GitHub repo with description files and then generating a website out of it.
